resources:
  - name: email-resource-source
    type: git
    source:
      uri: git@github.com:goutamtadi1/email-resource.git 
      private_key: {{g2c-git-key}}
      branch: golang_timeout 
  - name: send-an-email
    type: email
    source:
      smtp:
        host: smtp.gmail.com
        port: "587"
        username: xxxxxxxx 
        password: "#"
      from: xxxxx
      to: ["xxxxxx"]
resource_types:
  - name: email
    type: docker-image
    source:
      repository: pcfseceng/email-resource
jobs:
  - name: demo-email-an-artifact-sha
    plan:
      - get: email-resource-source
        trigger: false
      - task: demo-prep-sha-email
        file: email-resource-source/ci/demo-prep-sha-email.yml
        config:
          params:
            file_to_hash: email-resource-source/Dockerfile
            output_subject_file: generated-subject
            output_body_file: generated-body
      - put: send-an-email
        params:
          subject: email-out/generated-subject
          body: email-out/generated-body
